#!/bin/bash
i(){
  sudo apt update && sudo apt install $@
}

rm(){
  sudo apt update && sudo apt install $@ && sudo apt autoremove
}

upgrade(){
  sudo apt update && sudo apt upgrade && sudo apt autoremove
}


"$@"
