#!/bin/env dash

set -ex

update_cache() {
  case $PACKAGE_MANAGER in
  choco)
    choco list -lo | grep -v 'packages installed' | cut -d ' ' -f 1 |
      tail -n +2 >~/.cache/apw/installed
    ;;
  apt)
    (sudo apt list --installed | sed 's/\/.*$//g') >~/.cache/apw/installed
    ;;
  esac
}

fn_add() {
  case $PACKAGE_MANAGER in
  apt)
    echo "Updating database..."
    sudo apt update >/dev/null 2>&1
    sudo apt install "$@"
    ;;
  choco)
    choco install "$@"
    update_cache
    ;;
  esac
}

fn_del() {
  case $PACKAGE_MANAGER in
  apt)
    echo "Updating database..."
    sudo apt update >/dev/null 2>&1
    sudo apt purge "$@"
    sudo apt autoremove -y
    ;;
  choco)
    choco uninstall "$@"
    update_cache
    ;;
  esac
}

fn_upgrade() {
  case $PACKAGE_MANAGER in
  apt)
    echo "Updating database..."
    sudo apt update >/dev/null 2>&1
    sudo apt upgrade -y
    sudo apt autoremove -y
    ;;
  choco)
    choco upgrade all -y
    update_cache
    ;;
  esac
}

fn_info() {
  case $PACKAGE_MANAGER in
  apt)
    sudo apt list --installed
    ;;
  choco)
    if test ! -f ~/.cache/apw/installed; then
      update_cache
    fi
    cat ~/.cache/apw/installed
    ;;
  esac
}

main() {
  if test ! -d ~/.cache/apw/; then
    mkdir -p ~/.cache/apw/
  fi

  if test ! -f ~/.cache/apw/package_manager; then
    if apt -v >/dev/null 2>&1; then
      echo "apt" >~/.cache/apw/package_manager
    elif choco -v >/dev/null 2>&1; then
      echo "choco" >~/.cache/apw/package_manager
    fi
  fi

  PACKAGE_MANAGER=$(cat ~/.cache/apw/package_manager)

  if ! "$@" 2>/dev/null; then
    echo "arguments not recognised" >&2
  fi
}

main fn_"$*"
